name: Build legate.core
on: 
  push:
    branches-ignore:
      - gh-pages  # deployment target branch (this workflow should not exist on that branch anyway)
  pull_request:
    branches-ignore:
      - gh-pages  # deployment target branch (this workflow should not exist on that branch anyway)
env:
  COMMIT: ${{ github.event.pull_request.head.sha || github.sha }}
  PROJECT: github-numpy-ci
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Run CI build
        run: |
          /data/github-runner/legate-bin/setup.sh
          cd legate-ci
          cd github-ci/
          cd legate.numpy
          rm -rf ngc-artifacts
          ./build.sh > ${COMMIT}-build.log 2>&1
          cat *artifacts/*/*
      - name: Upload Build Log
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-log
          path: ./**/*build.log.gpg
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run CI tests
        run: |
          /data/github-runner/legate-bin/setup.sh
          cd legate-ci
          cd github-ci/
          cd legate.numpy
          if [[ ! -d ngc-artifacts ]]
          then
            mkdir ngc-artifacts
          else
            rm -rf ngc-artifacts/*
          fi
          ./test.sh > ${COMMIT}-test.log 2>&1
          cat *artifacts/*/*
      - name: Upload Build Log
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-log
          path: ./**/*build.log.gpg